blueprints/urls.py
"""Routes for Blueprints."""

from django.urls import path

from .views import regular_views
from .views.blueprint_list import BlueprintListJson

app_name = "blueprints"

urlpatterns = [
    path("", regular_views.index, name="index"),
    path(
        "modals/view_blueprint",
        regular_views.view_blueprint_modal,
        name="view_blueprint_modal",
    ),
    path(
        "modals/view_request",
        regular_views.view_request_modal,
        name="view_request_modal",
    ),
    path(
        "owners/add/character",
        regular_views.add_personal_blueprint_owner,
        name="add_personal_blueprint_owner",
    ),
    path(
        "owners/add/corporation",
        regular_views.add_corporation_blueprint_owner,
        name="add_corporate_blueprint_owner",
    ),
    path(
        "owners/user",
        regular_views.list_user_owners,
        name="list_user_owners",
    ),
    path(
        "owners/<int:owner_id>/remove",
        regular_views.remove_owner,
        name="remove_owner",
    ),
    path("blueprints", BlueprintListJson.as_view(), name="list_blueprints"),
    path("requests/user", regular_views.list_user_requests, name="list_user_requests"),
    path("requests/open", regular_views.list_open_requests, name="list_open_requests"),
    path("requests/add", regular_views.create_request, name="create_request"),
    path(
        "requests/<int:request_id>/open",
        regular_views.mark_request_open,
        name="request_open",
    ),
    path(
        "requests/<int:request_id>/fulfill",
        regular_views.mark_request_fulfilled,
        name="request_fulfilled",
    ),
    path(
        "requests/<int:request_id>/in_progress",
        regular_views.mark_request_in_progress,
        name="request_in_progress",
    ),
    path(
        "requests/<int:request_id>/cancel",
        regular_views.mark_request_cancelled,
        name="request_cancelled",
    ),
    path(
        "list_blueprints_ffd",
        regular_views.list_blueprints_ffd,
        name="list_blueprints_ffd",
    ),
]

blueprints/templates/blueprints/base.html
{% extends 'allianceauth/base.html' %}

{% load i18n %}

{% block page_title %}
    {% translate "Blueprint Library" %}
{% endblock %}

{% block content %}
    <div class="aa-blueprints">
        <h1 class="page-header text-center">{% translate "Blueprint Library" %}</h1>

        {% block details %}{% endblock %}
    </div>
{% endblock %}

blueprints/templates/blueprints/index.html
{% extends 'blueprints/base.html' %}

{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}
    <div>
        <ul class="nav nav-tabs" role="tablist" id="aa-blueprints-library-tabs">
            <li class="active">
                <a href="#tab-library" data-toggle="tab">{% translate "Library" %}</a>
            </li>
            {% if perms.blueprints.request_blueprints %}
                <li>
                    <a href="#tab-user-requests" data-toggle="tab">{% translate "My Requests" %}</a>
                </li>
            {% endif %}
            {% if perms.blueprints.manage_requests %}
                <li>
                    <a href="#tab-open-requests" data-toggle="tab">
                        {% translate "Open Requests" %}
                        {% if request_count %}
                            &nbsp;<span class="badge">{{ request_count }}</span>
                        {% endif %}
                    </a>
                </li>
            {% endif %}
            {% if perms.blueprints.add_personal_blueprint_owner or perms.blueprints.add_corporate_blueprint_owner %}
                <li>
                    <a href="#tab-manage-blueprints" data-toggle="tab">{% translate "Manage Blueprints" %}</a>
                </li>
            {% endif %}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active panel panel-default" id="tab-library">
                <div class="panel-body">
                    <table id="table-blueprints" style="width: 100%" class="table table-striped">
                        <thead>
                            <tr>
                                <th></th>
                                <th>{% translate "Type" %}</th>
                                <th><abbr title="{% translate 'Quantity' %}">{% translate "Qty" %}</abbr></th>
                                <th>{% translate "Owner" %}</th>
                                <th><span class="fas fa-gem pad-right"></span><abbr title="{% translate 'Material Efficiency' %}">
                                    {% comment %}Translators: Abbreviation for "Material Efficiency"{% endcomment %}
                                    {% translate 'ME' %}
                                </abbr></th>
                                <th><span class="fas fa-hourglass pad-right"></span><abbr title="{% translate 'Time Efficiency' %}">
                                    {% comment %}Translators: Abbreviation for "Time Efficiency"{% endcomment %}
                                    {% translate 'TE' %}
                                </abbr></th>
                                <th>{% translate "Original" %}</th>
                                <th>{% translate "Runs Remaining" %}</th>
                                <th></th>
                            </tr>
                        </thead>
                    </table>
                    <p class="text-muted">
                        {% translate "Blueprints in use are highlighted in blue." %}
                    </p>
                </div>
            </div>

            {% if perms.blueprints.request_blueprints %}
                <div class="tab-pane panel panel-default" id="tab-user-requests">
                    <div class="panel-body">
                        <table id="table-user-requests" style="width: 100%" class="table table-striped">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>{% translate "Type" %}</th>
                                    <th>{% translate "Runs" %}</th>
                                    <th>{% translate "Requested From" %}</th>
                                    <th></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            {% endif %}

            {% if perms.blueprints.manage_requests %}
                <div class="tab-pane panel panel-default" id="tab-open-requests">
                    <div class="panel-body">
                        <table id="table-open-requests" style="width: 100%" class="table table-striped">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>{% translate "Type" %}</th>
                                    <th>{% translate "Runs" %}</th>
                                    <th>{% translate "Requestor" %}</th>
                                    <th>{% translate "Requested From" %}</th>
                                    <th></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            {% endif %}


            {% if perms.blueprints.add_personal_blueprint_owner or perms.blueprints.add_corporate_blueprint_owner %}
                <div class="tab-pane panel panel-default" id="tab-manage-blueprints">
                    <div class="panel-body">
                        <div class="clearfix" style="margin-bottom: 1rem;">
                            <div class="pull-right">
                                {% if perms.blueprints.add_personal_blueprint_owner %}
                                    <a class="btn btn-success btn-tabs" href="{% url 'blueprints:add_personal_blueprint_owner' %}">
                                        {% translate "Add My Blueprints" %}
                                    </a>
                                {% endif %}
                                {% if perms.blueprints.add_corporate_blueprint_owner %}
                                    <a class="btn btn-success btn-tabs" href="{% url 'blueprints:add_corporate_blueprint_owner' %}">
                                        {% translate "Add Corporation Blueprints" %}
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        <table id="table-manage-blueprints" style="width: 100%" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>{% translate "Name" %}</th>
                                    <th>{% translate "Quantity" %}</th>
                                    <th></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    {% include 'blueprints/modals/modal_dialog.html' with name="ViewBlueprint" %}
    {% include 'blueprints/modals/modal_dialog.html' with name="ViewRequest" %}
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}

    <link rel="stylesheet" href="{% static 'blueprints/css/aa-bootstrap-fix.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'blueprints/css/blueprints.css' %}" type="text/css">
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    <script type="application/javascript" src="{% static 'blueprints/js/vendor/filterDropDown.min.js' %}" ></script>

    <script type="application/javascript">
        let listDataUrl = '{% url "blueprints:list_blueprints" %}';
        {% if active_tags %}
            listDataUrl += '?tags={{ active_tags|join:"," }}'
        {% endif %}

        let blueprintsSettings = {
            listDataUrl: listDataUrl,
            listDataFddUrl: '{% url "blueprints:list_blueprints_ffd" %}',
            openRequestListUrl: '{% url "blueprints:list_open_requests" %}',
            userRequestListUrl: '{% url "blueprints:list_user_requests" %}',
            inProgressRequestUrl: '{% url "blueprints:request_in_progress" request_id=12345 %}',
            cancelRequestUrl:'{% url "blueprints:request_cancelled" request_id=12345 %}',
            openRequestUrl: '{% url "blueprints:request_open" request_id=12345 %}',
            fulfillRequestUrl: '{% url "blueprints:request_fulfilled" request_id=12345 %}',
            viewBlueprintUrl: '{% url "blueprints:create_request" %}',
            listUserOwnerUrl: '{% url "blueprints:list_user_owners" %}',
            removeOwnerUrl: '{% url "blueprints:remove_owner" owner_id=12345 %}',
            viewBlueprintModalUrl: '{% url "blueprints:view_blueprint_modal" %}',
            viewRequestModalUrl: '{% url "blueprints:view_request_modal" %}',
            csrfToken: '{% csrf_token %}',
            canAddBlueprints: {% if perms.blueprints.request_blueprints %} true {% else %} false {% endif %},
            canViewLocations: {% if perms.blueprints.view_blueprint_locations %} true {% else %} false {% endif %},
            dataTablesPageLength: {{ data_tables_page_length }},
            dataTablesPaging: {{ data_tables_paging|yesno:"true,false" }},
            translation: {
                filterLocation: "{% translate 'Location' %}",
                filterOwner: "{% translate 'Owner' %}",
                filterIsOriginal: "{% translate 'Is BPO?' %}",
                viewBlueprint: "{% translate 'View Blueprint' %}",
                markRequestCancelled: "{% translate 'Mark Request as Cancelled' %}",
                markRequestFulfilled: "{% translate 'Mark Request as Fulfilled' %}",
                markRequestInProgress: "{% translate 'Mark Request as In Progress' %}",
                markRequestOpen: "{% translate 'Mark Request as Open' %}",
                createRequest: "{% translate 'Create Request' %}",
                requestInfo: "{% translate 'Request Information' %}",
                removeBlueprints: "{% translate 'Remove Blueprints' %}"
            }
        };

        $('#modalViewBlueprintContainer').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget)
            let ajax_url = button.data('ajax_url');

            $("#modalViewBlueprintContent").load(ajax_url)
        });

        $('#modalViewRequestContainer').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget)
            let ajax_url = button.data('ajax_url');

            $("#modalViewRequestContent").load(ajax_url)
        });
    </script>

    <script type="application/javascript" src="{% static 'blueprints/js/blueprint_list.js' %}" ></script>
    <script type="application/javascript" src="{% static 'blueprints/js/user_request_list.js' %}" ></script>
    <script type="application/javascript" src="{% static 'blueprints/js/open_request_list.js' %}" ></script>
    <script type="application/javascript" src="{% static 'blueprints/js/manage_blueprint_list.js' %}" ></script>

    <script type="application/javascript">
        if (location.hash) {
            $('a[href=\'' + location.hash + '\']').tab('show');
        }

        let activeTab = localStorage.getItem('activeTab');

        if (activeTab) {
            $('a[href="' + activeTab + '"]').tab('show');
        }

        $('#aa-blueprints-library-tabs').on('click', 'a[data-toggle=\'tab\']', function (e) {
            e.preventDefault()

            let tabName = this.getAttribute('href')

            if (history.pushState) {
                history.pushState(null, null, tabName)
            } else {
                location.hash = tabName
            }

            localStorage.setItem('activeTab', tabName)

            $(this).tab('show');

            return false;
        });

        $(window).on('popstate', function () {
            let anchor = location.hash || $('a[data-toggle=\'tab\']').first().attr('href');

            $('a[href=\'' + anchor + '\']').tab('show');
        });
    </script>
{% endblock %}

{% block extra_script %}
{% endblock %}